lzc-sdk-version: "0.1"
name: Blinko
package: lazycat.community.app.blinko
version: 1.0.5
description: An open-source, self-hosted personal AI note tool prioritizing privacy, built using TypeScript .
homepage: https://github.com/blinkospace/blinko
author: blinkospace
application:
    subdomain: blinko
    background_task: true
    public_path:
        - /
    routes:
        - /=http://blinko-website:1111/
services:
    blinko-website:
        image: docker.hlmirror.com/blinkospace/blinko:1.0.5
        environment:
            - NODE_ENV=production
            - NEXTAUTH_URL=https://${LAZYCAT_APP_DOMAIN}
            - NEXT_PUBLIC_BASE_URL=https://${LAZYCAT_APP_DOMAIN}
            - NEXTAUTH_SECRET=3VAQCMUjWZXk5+0wyQCtLAbmbFXteAh3DrC3TAy0zJA=
            - DATABASE_URL=postgresql://postgres:postgres@blinko_db:5432/blinko
            
        health_check:
            test:
                - CMD-SHELL
                - curl -f http://blinko-website:1111/
            start_period: 60s

        depends_on:
            - blinko_db

    blinko_db:
        container_name: blinko_db
        image: registry.lazycat.cloud/czyt/library/postgres:bc75bb4e26564157
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=blinko
            - TZ=Asia/Shanghai
        binds:
            - /lzcapp/var/db:/var/lib/postgresql/data
        health_check:
            test:
                - CMD-SHELL
                - pg_isready -U postgres -d blinko
            start_period: 90s
